// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/models/shared"
	"net/http"
)

type PatchAccountRequest struct {
	// Request body for patching (partially updating) an account
	BaseAccount shared.BaseAccount `request:"mediaType=application/json"`
	// Account ID
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
}

func (o *PatchAccountRequest) GetBaseAccount() shared.BaseAccount {
	if o == nil {
		return shared.BaseAccount{}
	}
	return o.BaseAccount
}

func (o *PatchAccountRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type PatchAccountResponse struct {
	// Response body for an account entity
	Account *shared.Account
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *PatchAccountResponse) GetAccount() *shared.Account {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *PatchAccountResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *PatchAccountResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchAccountResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchAccountResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchAccountResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
