// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/models/shared"
	"net/http"
)

type PatchContactRequest struct {
	// Request body for patching (partially updating) a contact
	BaseContact shared.BaseContact `request:"mediaType=application/json"`
	// Contact ID
	ContactID string `pathParam:"style=simple,explode=false,name=contactId"`
}

func (o *PatchContactRequest) GetBaseContact() shared.BaseContact {
	if o == nil {
		return shared.BaseContact{}
	}
	return o.BaseContact
}

func (o *PatchContactRequest) GetContactID() string {
	if o == nil {
		return ""
	}
	return o.ContactID
}

type PatchContactResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// Response body for a contact entity
	Contact *shared.Contact
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *PatchContactResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *PatchContactResponse) GetContact() *shared.Contact {
	if o == nil {
		return nil
	}
	return o.Contact
}

func (o *PatchContactResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchContactResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchContactResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchContactResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
