// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AccountCreate struct {
	// Addresses as a list of object, the element with index 0 is treated as the primary one.
	//
	Address        []BaseAddress `json:"address,omitempty"`
	CustomerNumber *string       `json:"customer_number,omitempty"`
	// Email addresses as a list of object, the element with index 0 is treated as the primary one.
	//
	Email []BaseEmail `json:"email,omitempty"`
	Name  string      `json:"name"`
	// Phone numbers as a list of object, the element with index 0 is treated as the primary one.
	//
	Phone   []BasePhone `json:"phone,omitempty"`
	Website *string     `json:"website,omitempty"`
}

func (o *AccountCreate) GetAddress() []BaseAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *AccountCreate) GetCustomerNumber() *string {
	if o == nil {
		return nil
	}
	return o.CustomerNumber
}

func (o *AccountCreate) GetEmail() []BaseEmail {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AccountCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *AccountCreate) GetPhone() []BasePhone {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *AccountCreate) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}
