// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BasePhone struct {
	ID    *string  `json:"_id,omitempty"`
	Tags  []string `json:"_tags,omitempty"`
	Phone string   `json:"phone"`
}

func (o *BasePhone) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *BasePhone) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *BasePhone) GetPhone() string {
	if o == nil {
		return ""
	}
	return o.Phone
}
