// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/pkg/utils"
)

type DollarRelation struct {
	Tags     []string `json:"_tags,omitempty"`
	EntityID string   `json:"entity_id"`
}

func (o *DollarRelation) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *DollarRelation) GetEntityID() string {
	if o == nil {
		return ""
	}
	return o.EntityID
}

type BaseRelation struct {
	DollarRelation       []DollarRelation `json:"$relation,omitempty"`
	AdditionalProperties interface{}      `additionalProperties:"true" json:"-"`
}

func (b BaseRelation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BaseRelation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BaseRelation) GetDollarRelation() []DollarRelation {
	if o == nil {
		return nil
	}
	return o.DollarRelation
}

func (o *BaseRelation) GetAdditionalProperties() interface{} {
	if o == nil {
		return nil
	}
	return o.AdditionalProperties
}
