// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BaseAccount struct {
	// Addresses as a list of object, the element with index 0 is treated as the primary one.
	//
	Address        []BaseAddress `json:"address,omitempty"`
	CustomerNumber *string       `json:"customer_number,omitempty"`
	// Email addresses as a list of object, the element with index 0 is treated as the primary one.
	//
	Email []BaseEmail `json:"email,omitempty"`
	Name  *string     `json:"name,omitempty"`
	// Phone numbers as a list of object, the element with index 0 is treated as the primary one.
	//
	Phone   []BasePhone `json:"phone,omitempty"`
	Website *string     `json:"website,omitempty"`
}

func (o *BaseAccount) GetAddress() []BaseAddress {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *BaseAccount) GetCustomerNumber() *string {
	if o == nil {
		return nil
	}
	return o.CustomerNumber
}

func (o *BaseAccount) GetEmail() []BaseEmail {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *BaseAccount) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *BaseAccount) GetPhone() []BasePhone {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *BaseAccount) GetWebsite() *string {
	if o == nil {
		return nil
	}
	return o.Website
}
