// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BaseEmail struct {
	ID    *string  `json:"_id,omitempty"`
	Tags  []string `json:"_tags,omitempty"`
	Email string   `json:"email"`
}

func (o *BaseEmail) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *BaseEmail) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *BaseEmail) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}
