// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type BaseRelation struct {
	DollarRelation       []DollarRelation `tfsdk:"dollar_relation"`
	AdditionalProperties types.String     `tfsdk:"additional_properties"`
}
