// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type BaseEmail struct {
	ID    types.String   `tfsdk:"id"`
	Tags  []types.String `tfsdk:"tags"`
	Email types.String   `tfsdk:"email"`
}
