// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetContactRequest struct {
	// Contact ID
	ContactID string `pathParam:"style=simple,explode=false,name=contactId"`
	// Hydrates entities in relations when passed true
	Hydrate *bool `queryParam:"style=form,explode=true,name=hydrate"`
}

func (o *GetContactRequest) GetContactID() string {
	if o == nil {
		return ""
	}
	return o.ContactID
}

func (o *GetContactRequest) GetHydrate() *bool {
	if o == nil {
		return nil
	}
	return o.Hydrate
}

type GetContactResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// Response body for a contact entity
	Contact *shared.Contact
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *GetContactResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *GetContactResponse) GetContact() *shared.Contact {
	if o == nil {
		return nil
	}
	return o.Contact
}

func (o *GetContactResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetContactResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetContactResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetContactResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
