// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateAccountRequest struct {
	// Request body for updating (completly replacing) an account
	AccountCreate shared.AccountCreate `request:"mediaType=application/json"`
	// Account ID
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
}

func (o *UpdateAccountRequest) GetAccountCreate() shared.AccountCreate {
	if o == nil {
		return shared.AccountCreate{}
	}
	return o.AccountCreate
}

func (o *UpdateAccountRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

type UpdateAccountResponse struct {
	// Response body for an account entity
	Account *shared.Account
	// Any error based on client data errors
	ClientError *shared.ClientError
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *UpdateAccountResponse) GetAccount() *shared.Account {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *UpdateAccountResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *UpdateAccountResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAccountResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAccountResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateAccountResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
