// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-customer/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateContactRequest struct {
	// Request body for updating (completly replacing) a contact
	ContactCreate shared.ContactCreate `request:"mediaType=application/json"`
	// Contact ID
	ContactID string `pathParam:"style=simple,explode=false,name=contactId"`
}

func (o *UpdateContactRequest) GetContactCreate() shared.ContactCreate {
	if o == nil {
		return shared.ContactCreate{}
	}
	return o.ContactCreate
}

func (o *UpdateContactRequest) GetContactID() string {
	if o == nil {
		return ""
	}
	return o.ContactID
}

type UpdateContactResponse struct {
	// Any error based on client data errors
	ClientError *shared.ClientError
	// Response body for a contact entity
	Contact *shared.Contact
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Any error based on the server-side
	ServerError *shared.ServerError
}

func (o *UpdateContactResponse) GetClientError() *shared.ClientError {
	if o == nil {
		return nil
	}
	return o.ClientError
}

func (o *UpdateContactResponse) GetContact() *shared.Contact {
	if o == nil {
		return nil
	}
	return o.Contact
}

func (o *UpdateContactResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateContactResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateContactResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateContactResponse) GetServerError() *shared.ServerError {
	if o == nil {
		return nil
	}
	return o.ServerError
}
